const SENTENCES = [
  // GREETINGS (14)
  { en: "Hello! How are you?", is: "Sabai dee baw?", script: "สะบายดีบ่?", cat: "greetings" },
  { en: "I am fine, thank you.", is: "Khoi sabai dee, khob jai.", script: "ข้อยสะบายดี ขอบใจ.", cat: "greetings" },
  { en: "What is your name?", is: "Jao seu nyang?", script: "เจ้าชื่อหยัง?", cat: "greetings" },
  { en: "My name is Nong.", is: "Khoi seu Nong.", script: "ข้อยชื่อน้อง.", cat: "greetings" },
  { en: "Nice to meet you.", is: "Yin dee thi dai huu jak.", script: "ยินดีที่ได้ฮู้จัก.", cat: "greetings" },
  { en: "Goodbye! See you again.", is: "La korn! Jeuh kan mai.", script: "ลาก่อน! เจอกันใหม่.", cat: "greetings" },
  { en: "No problem at all.", is: "Baw pen yang.", script: "บ่เป็นหยัง.", cat: "greetings" },
  { en: "Where are you going?", is: "Jao pai sai?", script: "เจ้าไปไส?", cat: "greetings" },
  { en: "I am going to school.", is: "Khoi pai hong hian.", script: "ข้อยไปห้องเฮียน.", cat: "greetings" },
  { en: "Please come in.", is: "Khao maa dern.", script: "เข้ามาเดิน.", cat: "greetings" },
  { en: "Thank you very much.", is: "Khob jai laai.", script: "ขอบใจหลาย.", cat: "greetings" },
  { en: "Good morning!", is: "A-lun sa-wad!", script: "อรุณสวัสดิ์!", cat: "greetings" },
  { en: "Good night!", is: "Laeng khuen dee!", script: "แลงคืนดี!", cat: "greetings" },
  { en: "Sorry, I did not know.", is: "Khot thot, khoi baw huu.", script: "ขอโทษ ข้อยบ่ฮู้.", cat: "greetings" },

  // NUMBERS (13)
  { en: "I have two cats.", is: "Khoi mi maeo song tua.", script: "ข้อยมีแมวสองตัว.", cat: "numbers" },
  { en: "She is seven years old.", is: "Lao a-yu jet pi.", script: "เลาอายุเจ็ดปี.", cat: "numbers" },
  { en: "There are ten chickens.", is: "Mi kai sip tua.", script: "มีไก่สิบตัว.", cat: "numbers" },
  { en: "I want three mangoes.", is: "Khoi ao mak muang sam luk.", script: "ข้อยเอามะม่วงสามลูก.", cat: "numbers" },
  { en: "It costs twenty baht.", is: "Ra-kha sao baht.", script: "ราคาซาวบาท.", cat: "numbers" },
  { en: "One hundred stars in the sky.", is: "Mi dao nung hoiy nai fa.", script: "มีดาวหนึ่งฮ้อยในฟ้า.", cat: "numbers" },
  { en: "How many buffaloes do you have?", is: "Jao mi khwai jak tua?", script: "เจ้ามีควายจักตัว?", cat: "numbers" },
  { en: "I counted five frogs.", is: "Khoi nap kop dai ha tua.", script: "ข้อยนับกบได้ห้าตัว.", cat: "numbers" },
  { en: "My house has four rooms.", is: "Heuan khoi mi si hong.", script: "เฮือนข้อยมีสี่ห้อง.", cat: "numbers" },
  { en: "We wake up at six.", is: "Hao tuen hok mong.", script: "เฮาตื่นหกโมง.", cat: "numbers" },
  { en: "She sang twelve songs.", is: "Lao hong phleng sip song phleng.", script: "เลาฮ้องเพลงสิบสองเพลง.", cat: "numbers" },
  { en: "The fish costs fifty baht.", is: "Pa ra-kha ha sip baht.", script: "ปาราคาห้าสิบบาท.", cat: "numbers" },
  { en: "Zero is a number too.", is: "Sun pen tua lek duai.", script: "ศูนย์เป็นตัวเลขด้วย.", cat: "numbers" },
  { en: "My younger sibling is two years old.", is: "Nawng khoi a-yu song pi.", script: "น้องข้อยอายุสองปี.", cat: "numbers" },

  // COLORS (14)
  { en: "The sky is blue.", is: "Fa si fah.", script: "ฟ้าสีฟ้า.", cat: "colors" },
  { en: "The sun is yellow.", is: "Ta-wan si lueang.", script: "ตะวันสีเหลือง.", cat: "colors" },
  { en: "I like the color red.", is: "Khoi mak si daeng.", script: "ข้อยมักสีแดง.", cat: "colors" },
  { en: "The grass is green.", is: "Ya si khiao.", script: "หญ้าสีเขียว.", cat: "colors" },
  { en: "Her dress is pink.", is: "Suea pha lao si chomphuu.", script: "เสื้อผ้าเลาสีชมพู.", cat: "colors" },
  { en: "What color is the cat?", is: "Maeo si nyang?", script: "แมวสีหยัง?", cat: "colors" },
  { en: "The cat is black and white.", is: "Maeo si dam lae si khao.", script: "แมวสีดำและสีขาว.", cat: "colors" },
  { en: "I want the orange one.", is: "Khoi ao an si som.", script: "ข้อยเอาอันสีส้ม.", cat: "colors" },
  { en: "The flower is purple.", is: "Dok mai si muang.", script: "ดอกไม้สีม่วง.", cat: "colors" },
  { en: "Draw a brown bear.", is: "Khian mii si nam tan.", script: "เขียนหมีสีน้ำตาล.", cat: "colors" },
  { en: "The river is bright blue.", is: "Maenam si fah saluat.", script: "แม่น้ำสีฟ้าสลวด.", cat: "colors" },
  { en: "My shirt is dark green.", is: "Suea khoi si khiao kaem.", script: "เสื้อข้อยสีเขียวแก่.", cat: "colors" },
  { en: "Gold is a beautiful color.", is: "Si thong ngam laai.", script: "สีทองงามหลาย.", cat: "colors" },
  { en: "I painted the wall white.", is: "Khoi tha fa phong si khao.", script: "ข้อยทาฝาผนังสีขาว.", cat: "colors" },

  // ANIMALS (13)
  { en: "The buffalo is very big.", is: "Khwai nyai laai.", script: "ควายใหญ่หลาย.", cat: "animals" },
  { en: "I see a frog in the field.", is: "Khoi hen kop yu nai na.", script: "ข้อยเห็นกบอยู่ในนา.", cat: "animals" },
  { en: "The dog is barking.", is: "Ma hong.", script: "หมาฮ้อง.", cat: "animals" },
  { en: "There is a snake under the tree.", is: "Mi nguu yu tai ton mai.", script: "มีงูอยู่ใต้ต้นไม้.", cat: "animals" },
  { en: "The bird is flying in the sky.", is: "Nok bin yu nai fa.", script: "นกบินอยู่ในฟ้า.", cat: "animals" },
  { en: "I like elephants.", is: "Khoi mak sang.", script: "ข้อยมักช้าง.", cat: "animals" },
  { en: "The cat is sleeping.", is: "Maeo non yu.", script: "แมวนอนอยู่.", cat: "animals" },
  { en: "We caught a big fish.", is: "Hao dai pa nyai.", script: "เฮาได้ปาใหญ่.", cat: "animals" },
  { en: "A butterfly is on the flower.", is: "Phi suea yu bon dok mai.", script: "ผีเสื้ออยู่บนดอกไม้.", cat: "animals" },
  { en: "The monkey is eating a banana.", is: "Ling kin mak kuay.", script: "ลิงกินมะกล้วย.", cat: "animals" },
  { en: "There are many ants here.", is: "Mi mod laai yu ni.", script: "มีมดหลายอยู่นี้.", cat: "animals" },
  { en: "The chicken laid an egg.", is: "Kai ok khai.", script: "ไก่ออกไข่.", cat: "animals" },
  { en: "Do not be scared of the cat.", is: "Yaa kua maeo.", script: "ยากัวแมว.", cat: "animals" },

  // FOOD (14)
  { en: "Sticky rice is delicious.", is: "Khao niao sep laai.", script: "ข้าวเหนียวแซบหลาย.", cat: "food" },
  { en: "I want to eat papaya salad.", is: "Khoi yak kin tam mak hung.", script: "ข้อยอยากกินตำมะหุ่ง.", cat: "food" },
  { en: "The food is very spicy.", is: "Ahan phet laai.", script: "อาหารเผ็ดหลาย.", cat: "food" },
  { en: "This mango is sweet.", is: "Mak muang ni wan.", script: "มะม่วงนี้หวาน.", cat: "food" },
  { en: "I am hungry, let us eat.", is: "Khoi hiu khao, pai kin loe.", script: "ข้อยหิวข้าว ไปกินเลย.", cat: "food" },
  { en: "Grilled chicken smells good.", is: "Kai yang hom laai.", script: "ไก่ย่างหอมหลาย.", cat: "food" },
  { en: "Do you like spicy food?", is: "Jao mak ahan phet baw?", script: "เจ้ามักอาหารเผ็ดบ่?", cat: "food" },
  { en: "Mama is cooking.", is: "Mae am het khao.", script: "แม่กำลังเฮ็ดข้าว.", cat: "food" },
  { en: "This vegetable is bitter.", is: "Phak ni khom.", script: "ผักนี้ขม.", cat: "food" },
  { en: "I do not like sour taste.", is: "Khoi baw mak rot som.", script: "ข้อยบ่มักรสส้ม.", cat: "food" },
  { en: "Fermented fish paste is very Isan.", is: "Pla ra pen ahan isan laai.", script: "ปลาร้าเป็นอาหารอีสานหลาย.", cat: "food" },
  { en: "The egg is fried.", is: "Khai dao.", script: "ไข่ดาว.", cat: "food" },
  { en: "I am full now.", is: "Khoi im laeo.", script: "ข้อยอิ่มแล้ว.", cat: "food" },
  { en: "More chili please!", is: "Sai mak phet eek!", script: "ใส่มักเผ็ดอีก!", cat: "food" },

  // DRINKS (13)
  { en: "I want cold water.", is: "Khoi ao nam yen.", script: "ข้อยเอาน้ำเย็น.", cat: "drinks" },
  { en: "Do you want milk?", is: "Jao ao nom baw?", script: "เจ้าเอานมบ่?", cat: "drinks" },
  { en: "I am thirsty.", is: "Khoi hiu nam.", script: "ข้อยหิวน้ำ.", cat: "drinks" },
  { en: "This juice is very sweet.", is: "Nam mak mai ni wan laai.", script: "น้ำมักไม้นี้หวานหลาย.", cat: "drinks" },
  { en: "Can I have more water?", is: "Kho nam eek dai baw?", script: "ขอน้ำอีกได้บ่?", cat: "drinks" },
  { en: "Coconut water is delicious.", is: "Nam mak phao sep laai.", script: "น้ำมะพร้าวแซบหลาย.", cat: "drinks" },
  { en: "Hot tea warms you up.", is: "Nam sa hon un jai.", script: "น้ำชาฮ้อนอุ่นใจ.", cat: "drinks" },
  { en: "My glass is empty.", is: "Kaeo khoi mot laeo.", script: "แก้วข้อยหมดแล้ว.", cat: "drinks" },
  { en: "Drink water every day.", is: "Kin nam thuk meu.", script: "กินน้ำทุกมื้อ.", cat: "drinks" },
  { en: "I like sugarcane juice.", is: "Khoi mak nam oi.", script: "ข้อยมักน้ำอ้อย.", cat: "drinks" },
  { en: "The water is very cold.", is: "Nam yen laai.", script: "น้ำเย็นหลาย.", cat: "drinks" },
  { en: "I drink milk every morning.", is: "Khoi kin nom thuk sao.", script: "ข้อยกินนมทุกเช้า.", cat: "drinks" },
  { en: "Ice makes drinks cold.", is: "Nam khaeng het hai nam yen.", script: "น้ำแข็งเฮ็ดให้น้ำเย็น.", cat: "drinks" },

  // FAMILY (13)
  { en: "I love my mother.", is: "Khoi hak mae.", script: "ข้อยฮักแม่.", cat: "family" },
  { en: "My father is working.", is: "Phaw khoi het viak.", script: "พ่อข้อยเฮ็ดเวียก.", cat: "family" },
  { en: "My older brother is tall.", is: "Ai khoi suung.", script: "อ้ายข้อยสูง.", cat: "family" },
  { en: "My older sister is beautiful.", is: "Ee khoi ngam.", script: "อี่ข้อยงาม.", cat: "family" },
  { en: "I play with my younger sibling.", is: "Khoi len gap nawng.", script: "ข้อยเล่นกับน้อง.", cat: "family" },
  { en: "Grandpa tells us stories.", is: "Puu lao nithaan hai hao fang.", script: "ปู่เล่านิทานให้เฮาฟัง.", cat: "family" },
  { en: "Grandma cooks delicious food.", is: "Yaai het khao sep laai.", script: "ยายเฮ็ดข้าวแซบหลาย.", cat: "family" },
  { en: "My family is big.", is: "Khop khua khoi nyai.", script: "ครอบครัวข้อยใหญ่.", cat: "family" },
  { en: "I miss my mother.", is: "Khoi khit heung mae.", script: "ข้อยคิดฮอดแม่.", cat: "family" },
  { en: "My friend is named Daeng.", is: "Muu khoi seu Daeng.", script: "ม่ข้อยชื่อแดง.", cat: "family" },
  { en: "Uncle bought me a gift.", is: "Lung sue khong faak hai khoi.", script: "ลุงซื้อของฝากให้ข้อย.", cat: "family" },
  { en: "My teacher is very kind.", is: "Khru khoi jai dee laai.", script: "ครูข้อยใจดีหลาย.", cat: "family" },
  { en: "We live together happily.", is: "Hao yuu duai kan dee jai.", script: "เฮาอยู่ด้วยกันดีใจ.", cat: "family" },

  // BODY (13)
  { en: "My head hurts.", is: "Hua khoi jeep.", script: "หัวข้อยเจ็บ.", cat: "body" },
  { en: "Wash your hands before eating.", is: "Lang mue kon kin khao.", script: "ล้างมือก่อนกินข้าว.", cat: "body" },
  { en: "I have big eyes.", is: "Khoi mi ta nyai.", script: "ข้อยมีตาใหญ่.", cat: "body" },
  { en: "My stomach hurts.", is: "Thong khoi jeep.", script: "ท้องข้อยเจ็บ.", cat: "body" },
  { en: "She has long hair.", is: "Lao mi phom yaao.", script: "เลามีผมยาว.", cat: "body" },
  { en: "Cover your mouth when you cough.", is: "Pit pak muea ae.", script: "ปิดปากเมื่อไอ.", cat: "body" },
  { en: "I brush my teeth every day.", is: "Khoi than khaeo thuk meu.", script: "ข้อยถูแข้วทุกมื้อ.", cat: "body" },
  { en: "My ears can hear the music.", is: "Hu khoi dai yin dong don-tri.", script: "หูข้อยได้ยินเสียงดนตรี.", cat: "body" },
  { en: "I am not feeling well today.", is: "Khoi baw sabai meu nee.", script: "ข้อยบ่สะบายมื้อนี้.", cat: "body" },
  { en: "I fell and hurt my knee.", is: "Khoi lom lae hua khao jeep.", script: "ข้อยล้มแล้วหัวเข่าเจ็บ.", cat: "body" },
  { en: "My back is tired from sitting.", is: "Lang mueai phaw nang naan.", script: "หลังเหนื่อยเพราะนั่งนาน.", cat: "body" },
  { en: "My heart loves everyone.", is: "Hua jai khoi hak thuk khon.", script: "หัวใจข้อยฮักทุกคน.", cat: "body" },
  { en: "Clap your hands!", is: "Tap mue!", script: "ตบมือ!", cat: "body" },

  // CLOTHING (13)
  { en: "I wear a red shirt today.", is: "Khoi sai suea daeng meu nee.", script: "ข้อยใส่เสื้อแดงมื้อนี้.", cat: "clothing" },
  { en: "My shoes are dirty.", is: "Khoeng khoi sok-ka-prok.", script: "เกิบข้อยสกปรก.", cat: "clothing" },
  { en: "Put on your hat, it is hot.", is: "Sai muak, hon laai.", script: "ใส่หมวก ฮ้อนหลาย.", cat: "clothing" },
  { en: "Mama is washing the clothes.", is: "Mae sak pha.", script: "แม่ซักผ้า.", cat: "clothing" },
  { en: "The silk cloth is beautiful.", is: "Pha mai ngam laai.", script: "ผ้าไหมงามหลาย.", cat: "clothing" },
  { en: "I wear my school uniform.", is: "Khoi sai suea chut hian.", script: "ข้อยใส่เสื้อชุดเฮียน.", cat: "clothing" },
  { en: "These socks are clean.", is: "Thung thao ni sa-at.", script: "ถุงเท้านี้สะอาด.", cat: "clothing" },
  { en: "My pants are too big.", is: "Kang-keng khoi nyai kuon pai.", script: "กางเกงข้อยใหญ่เกินไป.", cat: "clothing" },
  { en: "She wears a pink dress.", is: "Lao sai suea pha si chomphuu.", script: "เลาใส่เสื้อผ้าสีชมพู.", cat: "clothing" },
  { en: "It is cold, wear a jacket.", is: "Naao laai, sai suea khlum.", script: "หนาวหลาย ใส่เสื้อคลุม.", cat: "clothing" },
  { en: "The Isan wrap skirt is lovely.", is: "Pha sin ngam laai.", script: "ผ้าซิ่นงามหลาย.", cat: "clothing" },
  { en: "I lost my glasses.", is: "Khoi hat waen ta.", script: "ข้อยหายแว่นตา.", cat: "clothing" },
  { en: "The bag is too heavy.", is: "Thung nak kuon pai.", script: "ถุงหนักเกินไป.", cat: "clothing" },

  // NATURE (13)
  { en: "The sun is very bright today.", is: "Ta-wan sawang laai meu nee.", script: "ตะวันสว่างหลายมื้อนี้.", cat: "nature" },
  { en: "The moon is beautiful tonight.", is: "Duen ngam laai khuen nee.", script: "เดือนงามหลายคืนนี้.", cat: "nature" },
  { en: "It is raining hard.", is: "Fon tok nyai.", script: "ฝนตกใหญ่.", cat: "nature" },
  { en: "The wind is blowing cool.", is: "Lom phad yen.", script: "ลมพัดเย็น.", cat: "nature" },
  { en: "I see many stars in the sky.", is: "Khoi hen dao laai nai fa.", script: "ข้อยเห็นดาวหลายในฟ้า.", cat: "nature" },
  { en: "The river is very wide.", is: "Maenam kuaang laai.", script: "แม่น้ำกว้างหลาย.", cat: "nature" },
  { en: "The mountain is very tall.", is: "Phu suung laai.", script: "ภูสูงหลาย.", cat: "nature" },
  { en: "The forest is cool and shady.", is: "Pa yen lae rom.", script: "ป่าเย็นและร่ม.", cat: "nature" },
  { en: "The flower smells sweet.", is: "Dok mai hom wan.", script: "ดอกไม้หอมหวาน.", cat: "nature" },
  { en: "Today the weather is hot.", is: "A-kat meu nee hon laai.", script: "อากาศมื้อนี้ฮ้อนหลาย.", cat: "nature" },
  { en: "Clouds are floating in the sky.", is: "Mek loi yu nai fa.", script: "เมฆลอยอยู่ในฟ้า.", cat: "nature" },
  { en: "The rice field is green.", is: "Na si khiao.", script: "นาสีเขียว.", cat: "nature" },
  { en: "The stone by the river is wet.", is: "Hin khang maenam piak.", script: "หินข้างแม่น้ำเปียก.", cat: "nature" },

  // HOME (13)
  { en: "Our house is by the river.", is: "Heuan hao yuu khang maenam.", script: "เฮือนเฮาอยู่ข้างแม่น้ำ.", cat: "home" },
  { en: "Please close the door.", is: "Pit pa-tuu duai.", script: "ปิดประตูด้วย.", cat: "home" },
  { en: "Open the window.", is: "Poet na-tang.", script: "เปิดหน้าต่าง.", cat: "home" },
  { en: "Mama is cooking in the kitchen.", is: "Mae het khao yu hong het khao.", script: "แม่เฮ็ดข้าวอยู่ห้องเฮ็ดข้าว.", cat: "home" },
  { en: "I am sleeping in my room.", is: "Khoi non yu hong khoi.", script: "ข้อยนอนอยู่ห้องข้อย.", cat: "home" },
  { en: "Sweep the floor please.", is: "Kwaat phuen duai.", script: "กวาดพื้นด้วย.", cat: "home" },
  { en: "The table has bowls and spoons.", is: "Bon to mi thuai lae buang.", script: "บนโต๊ะมีถ้วยและช้อน.", cat: "home" },
  { en: "My bed is very soft.", is: "Tiang khoi num laai.", script: "เตียงข้อยนุ่มหลาย.", cat: "home" },
  { en: "Turn on the light.", is: "Poet fai.", script: "เปิดไฟ.", cat: "home" },
  { en: "The bathroom is at the back.", is: "Hong nam yu lang heuan.", script: "ห้องน้ำอยู่หลังเฮือน.", cat: "home" },
  { en: "Climb the stairs carefully.", is: "Khuen khan dai duai khwam ra-wang.", script: "ขึ้นขั้นไดด้วยความระวัง.", cat: "home" },
  { en: "The roof is made of wood.", is: "Lang kha het duai mai.", script: "หลังคาเฮ็ดด้วยไม้.", cat: "home" },
  { en: "I use a pillow when sleeping.", is: "Khoi chai mawn muea non.", script: "ข้อยใช้หมอนเมื่อนอน.", cat: "home" },

  // VERBS (13)
  { en: "I eat sticky rice every day.", is: "Khoi kin khao niao thuk meu.", script: "ข้อยกินข้าวเหนียวทุกมื้อ.", cat: "verbs" },
  { en: "She is running in the field.", is: "Lao wing yu nai na.", script: "เลาวิ่งอยู่ในนา.", cat: "verbs" },
  { en: "I am studying at school.", is: "Khoi hian yu hong hian.", script: "ข้อยเฮียนอยู่ห้องเฮียน.", cat: "verbs" },
  { en: "We speak Isan at home.", is: "Hao vao phasa isan nai heuan.", script: "เฮาเว้าภาษาอีสานในเฮือน.", cat: "verbs" },
  { en: "She is singing a song.", is: "Lao hong phleng.", script: "เลาฮ้องเพลง.", cat: "verbs" },
  { en: "Father is working in the field.", is: "Phaw het viak yu nai na.", script: "พ่อเฮ็ดเวียกอยู่ในนา.", cat: "verbs" },
  { en: "I love my family.", is: "Khoi hak khop khua.", script: "ข้อยฮักครอบครัว.", cat: "verbs" },
  { en: "I like to play.", is: "Khoi mak len.", script: "ข้อยมักเล่น.", cat: "verbs" },
  { en: "The baby is crying.", is: "Dek noi hong hai.", script: "เด็กน้อยฮ้องไห้.", cat: "verbs" },
  { en: "We are laughing together.", is: "Hao hua duai kan.", script: "เฮาฮ่าด้วยกัน.", cat: "verbs" },
  { en: "She knows how to cook.", is: "Lao huu het khao.", script: "เลาฮู้เฮ็ดข้าว.", cat: "verbs" },
  { en: "Please give me some water.", is: "Hai nam khoi duai.", script: "ให้น้ำข้อยด้วย.", cat: "verbs" },
  { en: "I can see a fish in the water.", is: "Khoi hen pa yu nai nam.", script: "ข้อยเห็นปาอยู่ในน้ำ.", cat: "verbs" },

  // ADJECTIVES (13)
  { en: "The elephant is very big.", is: "Sang nyai laai.", script: "ช้างใหญ่หลาย.", cat: "adjectives" },
  { en: "The cat is small and cute.", is: "Maeo noi lae naa rak.", script: "แมวน้อยและน่ารัก.", cat: "adjectives" },
  { en: "The flower is beautiful.", is: "Dok mai ngam laai.", script: "ดอกไม้งามหลาย.", cat: "adjectives" },
  { en: "This food is very good.", is: "Ahan ni dee laai.", script: "อาหารนี้ดีหลาย.", cat: "adjectives" },
  { en: "The turtle walks very slowly.", is: "Tao dern saa laai.", script: "เต่าเดินซ้าหลาย.", cat: "adjectives" },
  { en: "Today is very hot.", is: "Meu nee hon laai.", script: "มื้อนี้ฮ้อนหลาย.", cat: "adjectives" },
  { en: "I am tired today.", is: "Khoi mueai meu nee.", script: "ข้อยเหนื่อยมื้อนี้.", cat: "adjectives" },
  { en: "I am so full!", is: "Khoi im laai!", script: "ข้อยอิ่มหลาย!", cat: "adjectives" },
  { en: "My bag is very heavy.", is: "Thung khoi nak laai.", script: "ถุงข้อยหนักหลาย.", cat: "adjectives" },
  { en: "The pillow is very soft.", is: "Mawn num laai.", script: "หมอนนุ่มหลาย.", cat: "adjectives" },
  { en: "This is a new school.", is: "Ni pen hong hian mai.", script: "นี้เป็นห้องเฮียนใหม่.", cat: "adjectives" },
  { en: "The school is near my house.", is: "Hong hian yuu kai heuan.", script: "ห้องเฮียนอยู่ใกล้เฮือน.", cat: "adjectives" },
  { en: "Playing games is so fun!", is: "Len len muan laai!", script: "เล่นเล่นสนุกหลาย!", cat: "adjectives" },

  // TIME (13)
  { en: "Today is a good day.", is: "Meu nee pen meu dee.", script: "มื้อนี้เป็นมื้อดี.", cat: "time" },
  { en: "Yesterday it rained.", is: "Meu waan fon tok.", script: "มื้อวานฝนตก.", cat: "time" },
  { en: "Tomorrow we go to school.", is: "Meu eun hao pai hong hian.", script: "มื้ออื่นเฮาไปห้องเฮียน.", cat: "time" },
  { en: "The moon comes out at night.", is: "Duen ok maa nai khuen.", script: "เดือนออกมาในคืน.", cat: "time" },
  { en: "Wake up early in the morning.", is: "Tuen sao waao.", script: "ตื่นเช้าเช้า.", cat: "time" },
  { en: "Every day I eat sticky rice.", is: "Thuk meu khoi kin khao niao.", script: "ทุกมื้อข้อยกินข้าวเหนียว.", cat: "time" },
  { en: "School starts at eight o'clock.", is: "Hong hian poem paet mong.", script: "ห้องเฮียนเปิดแปดโมง.", cat: "time" },
  { en: "I sleep for eight hours.", is: "Khoi non paet suamong.", script: "ข้อยนอนแปดซั่วโมง.", cat: "time" },
  { en: "How long does it take?", is: "Chai welaa naan thao dai?", script: "ใช้เวลานานเท่าได๋?", cat: "time" },
  { en: "I sometimes go fishing.", is: "Khoi bang khao pai haa pa.", script: "ข้อยบางคราวไปหาปา.", cat: "time" },
  { en: "She never eats spicy food.", is: "Lao baw khoi kin ahan phet.", script: "เลาบ่เคยกินอาหารเผ็ด.", cat: "time" },
  { en: "I am playing right now.", is: "Khoi am len diao nee.", script: "ข้อยกำลังเล่นเดี๋ยวนี้.", cat: "time" },
  { en: "This year I am seven years old.", is: "Pii nee khoi a-yu jet pi.", script: "ปีนี้ข้อยอายุเจ็ดปี.", cat: "time" },

  // EMOTIONS (14)
  { en: "I am very happy today.", is: "Khoi dee jai laai meu nee.", script: "ข้อยดีใจหลายมื้อนี้.", cat: "emotions" },
  { en: "I miss my grandma.", is: "Khoi khit heung yaai.", script: "ข้อยคิดฮอดยาย.", cat: "emotions" },
  { en: "Do not be scared.", is: "Yaa kua.", script: "ยากัว.", cat: "emotions" },
  { en: "I love my family so much.", is: "Khoi hak khop khua laai.", script: "ข้อยฮักครอบครัวหลาย.", cat: "emotions" },
  { en: "The baby is crying loudly.", is: "Dek noi hong hai dang.", script: "เด็กน้อยฮ้องไห้ดัง.", cat: "emotions" },
  { en: "I am bored of staying home.", is: "Khoi buea yuu heuan.", script: "ข้อยเบื่ออยู่เฮือน.", cat: "emotions" },
  { en: "She is shy and does not speak.", is: "Lao aai lae baw vao.", script: "เลาอายและบ่เว้า.", cat: "emotions" },
  { en: "We are excited to play.", is: "Hao tuen ten thi ja pai len.", script: "เฮาตื่นเต้นที่จะไปเล่น.", cat: "emotions" },
  { en: "I am proud of my work.", is: "Khoi phum jai nai viak khoi.", script: "ข้อยภูมิใจในเวียกข้อย.", cat: "emotions" },
  { en: "I feel lonely today.", is: "Khoi ruu seuk ngeow meu nee.", script: "ข้อยรู้สึกเหงามื้อนี้.", cat: "emotions" },
  { en: "I am worried about the test.", is: "Khoi hen jai kiao kap kan sop.", script: "ข้อยเป็นห่วงเกี่ยวกับการสอบ.", cat: "emotions" },
  { en: "Thank you, I am very grateful.", is: "Khob jai, khoi khob jai laai.", script: "ขอบใจ ข้อยขอบใจหลาย.", cat: "emotions" },
  { en: "We laugh together every day.", is: "Hao hua duai kan thuk meu.", script: "เฮาฮ่าด้วยกันทุกมื้อ.", cat: "emotions" },
  { en: "I like you!", is: "Khoi mak jao!", script: "ข้อยมักเจ้า!", cat: "emotions" },
];
