const WORDS = [
  // GREETINGS (20)
  { en: "hello / how are you", is: "sabai dee", script: "สะบายดี", cat: "greetings" },
  { en: "goodbye", is: "la korn", script: "ลาก่อน", cat: "greetings" },
  { en: "thank you", is: "khob jai", script: "ขอบใจ", cat: "greetings" },
  { en: "sorry / excuse me", is: "khot thot", script: "ขอโทษ", cat: "greetings" },
  { en: "yes", is: "men", script: "แม่น", cat: "greetings" },
  { en: "no", is: "baw", script: "บ่", cat: "greetings" },
  { en: "I / me", is: "khoi", script: "ข้อย", cat: "greetings" },
  { en: "you", is: "jao", script: "เจ้า", cat: "greetings" },
  { en: "fine / well", is: "sabai dee", script: "สะบายดี", cat: "greetings" },
  { en: "no problem", is: "baw pen yang", script: "บ่เป็นหยัง", cat: "greetings" },
  { en: "welcome", is: "yin dee ton hap", script: "ยินดีต้อนรับ", cat: "greetings" },
  { en: "nice to meet you", is: "yin dee thi dai huu jak", script: "ยินดีที่ได้ฮู้จัก", cat: "greetings" },
  { en: "what is your name?", is: "jao seu nyang?", script: "เจ้าชื่อหยัง?", cat: "greetings" },
  { en: "my name is...", is: "khoi seu...", script: "ข้อยชื่อ...", cat: "greetings" },
  { en: "how old are you?", is: "jao a-yu thao dai?", script: "เจ้าอายุเท่าได๋?", cat: "greetings" },
  { en: "good morning", is: "a-lun sa-wad", script: "อรุณสวัสดิ์", cat: "greetings" },
  { en: "good night", is: "laeng khuen dee", script: "แลงคืนดี", cat: "greetings" },
  { en: "see you again", is: "jeuh kan mai", script: "เจอกันใหม่", cat: "greetings" },
  { en: "where are you going?", is: "jao pai sai?", script: "เจ้าไปไส?", cat: "greetings" },
  { en: "come in", is: "khao ma", script: "เข้ามา", cat: "greetings" },

  // NUMBERS (20)
  { en: "one", is: "nung", script: "หนึ่ง", cat: "numbers" },
  { en: "two", is: "song", script: "สอง", cat: "numbers" },
  { en: "three", is: "sam", script: "สาม", cat: "numbers" },
  { en: "four", is: "si", script: "สี่", cat: "numbers" },
  { en: "five", is: "ha", script: "ห้า", cat: "numbers" },
  { en: "six", is: "hok", script: "หก", cat: "numbers" },
  { en: "seven", is: "jet", script: "เจ็ด", cat: "numbers" },
  { en: "eight", is: "paet", script: "แปด", cat: "numbers" },
  { en: "nine", is: "kao", script: "เก้า", cat: "numbers" },
  { en: "ten", is: "sip", script: "สิบ", cat: "numbers" },
  { en: "eleven", is: "sip et", script: "สิบเอ็ด", cat: "numbers" },
  { en: "twelve", is: "sip song", script: "สิบสอง", cat: "numbers" },
  { en: "fifteen", is: "sip ha", script: "สิบห้า", cat: "numbers" },
  { en: "twenty", is: "sao", script: "ซาว", cat: "numbers" },
  { en: "thirty", is: "sam sip", script: "สามสิบ", cat: "numbers" },
  { en: "fifty", is: "ha sip", script: "ห้าสิบ", cat: "numbers" },
  { en: "one hundred", is: "nung hoiy", script: "หนึ่งฮ้อย", cat: "numbers" },
  { en: "one thousand", is: "nung phan", script: "หนึ่งพัน", cat: "numbers" },
  { en: "zero", is: "sun", script: "ศูนย์", cat: "numbers" },
  { en: "how many?", is: "jak an?", script: "จักอัน?", cat: "numbers" },

  // COLORS (20)
  { en: "red", is: "daeng", script: "แดง", cat: "colors" },
  { en: "blue", is: "fah", script: "ฟ้า", cat: "colors" },
  { en: "yellow", is: "lueang", script: "เหลือง", cat: "colors" },
  { en: "green", is: "khiao", script: "เขียว", cat: "colors" },
  { en: "white", is: "khao", script: "ขาว", cat: "colors" },
  { en: "black", is: "dam", script: "ดำ", cat: "colors" },
  { en: "orange", is: "som", script: "ส้ม", cat: "colors" },
  { en: "pink", is: "chomphuu", script: "ชมพู", cat: "colors" },
  { en: "purple", is: "muang", script: "ม่วง", cat: "colors" },
  { en: "brown", is: "nam tan", script: "น้ำตาล", cat: "colors" },
  { en: "grey", is: "thao", script: "เทา", cat: "colors" },
  { en: "gold", is: "thong", script: "ทอง", cat: "colors" },
  { en: "silver", is: "ngoen", script: "เงิน", cat: "colors" },
  { en: "dark blue", is: "nam ngoen", script: "น้ำเงิน", cat: "colors" },
  { en: "light green", is: "khiao awn", script: "เขียวอ่อน", cat: "colors" },
  { en: "dark red", is: "daeng kaem", script: "แดงแก่", cat: "colors" },
  { en: "what color?", is: "si nyang?", script: "สีหยัง?", cat: "colors" },
  { en: "bright / vivid", is: "saluat", script: "สลวด", cat: "colors" },
  { en: "light colored", is: "si awn", script: "สีอ่อน", cat: "colors" },
  { en: "dark colored", is: "si kaem", script: "สีแก่", cat: "colors" },

  // ANIMALS (20)
  { en: "buffalo", is: "khwai", script: "ควาย", cat: "animals" },
  { en: "elephant", is: "sang", script: "ช้าง", cat: "animals" },
  { en: "dog", is: "ma", script: "หมา", cat: "animals" },
  { en: "cat", is: "maeo", script: "แมว", cat: "animals" },
  { en: "fish", is: "pa", script: "ปา", cat: "animals" },
  { en: "chicken", is: "kai", script: "ไก่", cat: "animals" },
  { en: "pig", is: "mu", script: "หมู", cat: "animals" },
  { en: "cow", is: "ngua", script: "วัว", cat: "animals" },
  { en: "duck", is: "pet", script: "เป็ด", cat: "animals" },
  { en: "frog", is: "kop", script: "กบ", cat: "animals" },
  { en: "snake", is: "nguu", script: "งู", cat: "animals" },
  { en: "monkey", is: "ling", script: "ลิง", cat: "animals" },
  { en: "bird", is: "nok", script: "นก", cat: "animals" },
  { en: "rabbit", is: "kae", script: "แกะ", cat: "animals" },
  { en: "mosquito", is: "yung", script: "ยุง", cat: "animals" },
  { en: "butterfly", is: "phi suea", script: "ผีเสื้อ", cat: "animals" },
  { en: "horse", is: "ma", script: "ม้า", cat: "animals" },
  { en: "tiger", is: "suea", script: "เสือ", cat: "animals" },
  { en: "lizard", is: "kai noi", script: "กิ้งก่า", cat: "animals" },
  { en: "ant", is: "mod", script: "มด", cat: "animals" },

  // FOOD (20)
  { en: "rice (cooked sticky)", is: "khao niao", script: "ข้าวเหนียว", cat: "food" },
  { en: "papaya salad (Isan)", is: "tam mak hung", script: "ตำมะหุ่ง", cat: "food" },
  { en: "grilled chicken", is: "kai yang", script: "ไก่ย่าง", cat: "food" },
  { en: "delicious", is: "sep", script: "แซบ", cat: "food" },
  { en: "spicy", is: "phet", script: "เผ็ด", cat: "food" },
  { en: "sweet", is: "wan", script: "หวาน", cat: "food" },
  { en: "sour", is: "som", script: "ส้ม", cat: "food" },
  { en: "salty", is: "kem", script: "เค็ม", cat: "food" },
  { en: "bitter", is: "khom", script: "ขม", cat: "food" },
  { en: "egg", is: "khai", script: "ไข่", cat: "food" },
  { en: "vegetable", is: "phak", script: "ผัก", cat: "food" },
  { en: "fruit", is: "mak mai", script: "มักไม้", cat: "food" },
  { en: "mango", is: "mak muang", script: "มะม่วง", cat: "food" },
  { en: "banana", is: "mak kuay", script: "มะกล้วย", cat: "food" },
  { en: "noodles", is: "kway tiao", script: "ก๋วยเตี๋ยว", cat: "food" },
  { en: "soup / broth", is: "tom", script: "ต้ม", cat: "food" },
  { en: "salt", is: "klua", script: "เกลือ", cat: "food" },
  { en: "chili", is: "mak phet", script: "มักเผ็ด", cat: "food" },
  { en: "fermented fish paste", is: "pla ra", script: "ปลาร้า", cat: "food" },
  { en: "I am hungry", is: "khoi hiu khao", script: "ข้อยหิวข้าว", cat: "food" },

  // DRINKS (20)
  { en: "water", is: "nam", script: "น้ำ", cat: "drinks" },
  { en: "milk", is: "nom", script: "นม", cat: "drinks" },
  { en: "juice", is: "nam mak mai", script: "น้ำมักไม้", cat: "drinks" },
  { en: "tea", is: "nam sa", script: "น้ำชา", cat: "drinks" },
  { en: "coconut water", is: "nam mak phao", script: "น้ำมะพร้าว", cat: "drinks" },
  { en: "cold water", is: "nam yen", script: "น้ำเย็น", cat: "drinks" },
  { en: "hot water", is: "nam hon", script: "น้ำฮ้อน", cat: "drinks" },
  { en: "sweet drink", is: "nam wan", script: "น้ำหวาน", cat: "drinks" },
  { en: "I am thirsty", is: "khoi hiu nam", script: "ข้อยหิวน้ำ", cat: "drinks" },
  { en: "to drink", is: "kin nam", script: "กินน้ำ", cat: "drinks" },
  { en: "cup / glass", is: "kaeo", script: "แก้ว", cat: "drinks" },
  { en: "bottle", is: "kuat", script: "ขวด", cat: "drinks" },
  { en: "sugarcane juice", is: "nam oi", script: "น้ำอ้อย", cat: "drinks" },
  { en: "orange juice", is: "nam mak kieng", script: "น้ำมักเกลี้ยง", cat: "drinks" },
  { en: "ice", is: "nam khaeng", script: "น้ำแข็ง", cat: "drinks" },
  { en: "more water please", is: "kho nam eek", script: "ขอน้ำอีก", cat: "drinks" },
  { en: "delicious drink", is: "nam sep", script: "น้ำแซบ", cat: "drinks" },
  { en: "soup", is: "nam tom", script: "น้ำต้ม", cat: "drinks" },
  { en: "coffee", is: "kaa fae", script: "กาแฟ", cat: "drinks" },
  { en: "soy milk", is: "nom thua", script: "นมถั่ว", cat: "drinks" },

  // FAMILY (20)
  { en: "mother", is: "mae", script: "แม่", cat: "family" },
  { en: "father", is: "phaw", script: "พ่อ", cat: "family" },
  { en: "older brother", is: "ai", script: "อ้าย", cat: "family" },
  { en: "older sister", is: "ee", script: "อี่", cat: "family" },
  { en: "younger sibling", is: "nawng", script: "น้อง", cat: "family" },
  { en: "grandfather (maternal)", is: "ta", script: "ตา", cat: "family" },
  { en: "grandmother (maternal)", is: "yaai", script: "ยาย", cat: "family" },
  { en: "grandfather (paternal)", is: "puu", script: "ปู่", cat: "family" },
  { en: "grandmother (paternal)", is: "yaa", script: "ย่า", cat: "family" },
  { en: "uncle (older)", is: "lung", script: "ลุง", cat: "family" },
  { en: "aunt (older)", is: "paa", script: "ป้า", cat: "family" },
  { en: "uncle (younger)", is: "aa", script: "อา", cat: "family" },
  { en: "child", is: "luuk", script: "ลูก", cat: "family" },
  { en: "family", is: "khop khua", script: "ครอบครัว", cat: "family" },
  { en: "friend", is: "muu", script: "ม่", cat: "family" },
  { en: "husband", is: "phua", script: "ผัว", cat: "family" },
  { en: "wife", is: "mia", script: "เมีย", cat: "family" },
  { en: "cousin", is: "laan", script: "หลาน", cat: "family" },
  { en: "neighbor", is: "kheu bang", script: "คื่อบ้าน", cat: "family" },
  { en: "teacher", is: "khru", script: "ครู", cat: "family" },

  // BODY (20)
  { en: "head", is: "hua", script: "หัว", cat: "body" },
  { en: "hair", is: "phom", script: "ผม", cat: "body" },
  { en: "eye", is: "ta", script: "ตา", cat: "body" },
  { en: "ear", is: "hu", script: "หู", cat: "body" },
  { en: "nose", is: "da-muk", script: "ดั้งมูก", cat: "body" },
  { en: "mouth", is: "pak", script: "ปาก", cat: "body" },
  { en: "tooth", is: "khaeo", script: "แข้ว", cat: "body" },
  { en: "tongue", is: "lin", script: "ลิ้น", cat: "body" },
  { en: "neck", is: "kho", script: "ขอ", cat: "body" },
  { en: "hand", is: "mue", script: "มือ", cat: "body" },
  { en: "finger", is: "niu mue", script: "นิ้วมือ", cat: "body" },
  { en: "foot / leg", is: "khaa", script: "ขา", cat: "body" },
  { en: "belly / stomach", is: "thong", script: "ท้อง", cat: "body" },
  { en: "back", is: "lang", script: "หลัง", cat: "body" },
  { en: "heart", is: "hua jai", script: "หัวใจ", cat: "body" },
  { en: "face", is: "naa", script: "หน้า", cat: "body" },
  { en: "shoulder", is: "baa", script: "บ่า", cat: "body" },
  { en: "knee", is: "hua khao", script: "หัวเข่า", cat: "body" },
  { en: "it hurts", is: "jeep", script: "เจ็บ", cat: "body" },
  { en: "I am sick", is: "khoi baw sabai", script: "ข้อยบ่สะบาย", cat: "body" },

  // CLOTHING (20)
  { en: "shirt", is: "suea", script: "เสื้อ", cat: "clothing" },
  { en: "pants / trousers", is: "kang-keng", script: "กางเกง", cat: "clothing" },
  { en: "skirt", is: "kha-nung", script: "กระโปรง", cat: "clothing" },
  { en: "shoes", is: "khoeng", script: "เกิบ", cat: "clothing" },
  { en: "sandals", is: "khoeng thaeo", script: "เกิบแตะ", cat: "clothing" },
  { en: "socks", is: "thung thao", script: "ถุงเท้า", cat: "clothing" },
  { en: "hat", is: "muak", script: "หมวก", cat: "clothing" },
  { en: "scarf", is: "pha phon kho", script: "ผ้าพันคอ", cat: "clothing" },
  { en: "dress", is: "suea pha", script: "เสื้อผ้า", cat: "clothing" },
  { en: "jacket", is: "suea khlum", script: "เสื้อคลุม", cat: "clothing" },
  { en: "Isan silk cloth", is: "pha mai", script: "ผ้าไหม", cat: "clothing" },
  { en: "traditional wrap skirt", is: "pha sin", script: "ผ้าซิ่น", cat: "clothing" },
  { en: "underwear", is: "suea nai", script: "เสื้อใน", cat: "clothing" },
  { en: "gloves", is: "thung mue", script: "ถุงมือ", cat: "clothing" },
  { en: "bag", is: "thung", script: "ถุง", cat: "clothing" },
  { en: "glasses", is: "waen ta", script: "แว่นตา", cat: "clothing" },
  { en: "uniform", is: "suea chut", script: "เสื้อชุด", cat: "clothing" },
  { en: "to wear", is: "sai", script: "ใส่", cat: "clothing" },
  { en: "to wash clothes", is: "sak pha", script: "ซักผ้า", cat: "clothing" },
  { en: "clean", is: "sa-at", script: "สะอาด", cat: "clothing" },

  // NATURE (20)
  { en: "sun", is: "ta-wan", script: "ตะวัน", cat: "nature" },
  { en: "moon", is: "duen", script: "เดือน", cat: "nature" },
  { en: "star", is: "dao", script: "ดาว", cat: "nature" },
  { en: "sky", is: "fa", script: "ฟ้า", cat: "nature" },
  { en: "cloud", is: "mek", script: "เมฆ", cat: "nature" },
  { en: "rain", is: "fon", script: "ฝน", cat: "nature" },
  { en: "wind", is: "lom", script: "ลม", cat: "nature" },
  { en: "river", is: "maenam", script: "แม่น้ำ", cat: "nature" },
  { en: "mountain", is: "phu", script: "ภู", cat: "nature" },
  { en: "tree", is: "ton mai", script: "ต้นไม้", cat: "nature" },
  { en: "flower", is: "dok mai", script: "ดอกไม้", cat: "nature" },
  { en: "grass / field", is: "ya", script: "หญ้า", cat: "nature" },
  { en: "rice field", is: "na", script: "นา", cat: "nature" },
  { en: "forest", is: "pa", script: "ป่า", cat: "nature" },
  { en: "stone / rock", is: "hin", script: "หิน", cat: "nature" },
  { en: "fire", is: "fai", script: "ไฟ", cat: "nature" },
  { en: "earth / soil", is: "din", script: "ดิน", cat: "nature" },
  { en: "pond / lake", is: "nong", script: "หนอง", cat: "nature" },
  { en: "hot (weather)", is: "hon", script: "ฮ้อน", cat: "nature" },
  { en: "cool / cold", is: "naao", script: "หนาว", cat: "nature" },

  // HOME (20)
  { en: "house", is: "heuan", script: "เฮือน", cat: "home" },
  { en: "room", is: "hong", script: "ห้อง", cat: "home" },
  { en: "door", is: "pa-tuu", script: "ประตู", cat: "home" },
  { en: "window", is: "na-tang", script: "หน้าต่าง", cat: "home" },
  { en: "floor", is: "phuen", script: "พื้น", cat: "home" },
  { en: "roof", is: "lang kha", script: "หลังคา", cat: "home" },
  { en: "kitchen", is: "hong het khao", script: "ห้องเฮ็ดข้าว", cat: "home" },
  { en: "bedroom", is: "hong non", script: "ห้องนอน", cat: "home" },
  { en: "bathroom", is: "hong nam", script: "ห้องน้ำ", cat: "home" },
  { en: "stairs", is: "khan dai", script: "ขั้นได", cat: "home" },
  { en: "table", is: "to", script: "โต๊ะ", cat: "home" },
  { en: "chair", is: "khaao-ii", script: "เก้าอี้", cat: "home" },
  { en: "bed", is: "tiang", script: "เตียง", cat: "home" },
  { en: "pillow", is: "mawn", script: "หมอน", cat: "home" },
  { en: "blanket", is: "pha hom", script: "ผ้าห่ม", cat: "home" },
  { en: "stove", is: "tao", script: "เตา", cat: "home" },
  { en: "bowl", is: "thuai", script: "ถ้วย", cat: "home" },
  { en: "spoon", is: "buang", script: "ช้อน", cat: "home" },
  { en: "broom", is: "mai kwaat", script: "ไม้กวาด", cat: "home" },
  { en: "lamp / light", is: "fai", script: "ไฟ", cat: "home" },

  // VERBS (20)
  { en: "to eat", is: "kin", script: "กิน", cat: "verbs" },
  { en: "to drink", is: "kin nam", script: "กินน้ำ", cat: "verbs" },
  { en: "to sleep", is: "non", script: "นอน", cat: "verbs" },
  { en: "to walk", is: "dern", script: "เดิน", cat: "verbs" },
  { en: "to run", is: "wing", script: "วิ่ง", cat: "verbs" },
  { en: "to play", is: "len", script: "เล่น", cat: "verbs" },
  { en: "to study", is: "hian", script: "เฮียน", cat: "verbs" },
  { en: "to speak / talk", is: "vao", script: "เว้า", cat: "verbs" },
  { en: "to do / make", is: "het", script: "เฮ็ด", cat: "verbs" },
  { en: "to love", is: "hak", script: "ฮัก", cat: "verbs" },
  { en: "to like", is: "mak", script: "มัก", cat: "verbs" },
  { en: "to go", is: "pai", script: "ไป", cat: "verbs" },
  { en: "to come", is: "maa", script: "มา", cat: "verbs" },
  { en: "to see / look", is: "hen", script: "เห็น", cat: "verbs" },
  { en: "to sing", is: "hong phleng", script: "ฮ้องเพลง", cat: "verbs" },
  { en: "to work", is: "het viak", script: "เฮ็ดเวียก", cat: "verbs" },
  { en: "to cry", is: "hong hai", script: "ฮ้องไห้", cat: "verbs" },
  { en: "to laugh", is: "hua", script: "ฮ่า", cat: "verbs" },
  { en: "to give", is: "hai", script: "ให้", cat: "verbs" },
  { en: "to know", is: "huu", script: "ฮู้", cat: "verbs" },

  // ADJECTIVES (20)
  { en: "big", is: "nyai", script: "ใหญ่", cat: "adjectives" },
  { en: "small", is: "noi", script: "น้อย", cat: "adjectives" },
  { en: "beautiful", is: "ngam", script: "งาม", cat: "adjectives" },
  { en: "good", is: "dee", script: "ดี", cat: "adjectives" },
  { en: "bad", is: "baw dee", script: "บ่ดี", cat: "adjectives" },
  { en: "fast", is: "waai", script: "ไว", cat: "adjectives" },
  { en: "slow", is: "saa", script: "ซ้า", cat: "adjectives" },
  { en: "hot", is: "hon", script: "ฮ้อน", cat: "adjectives" },
  { en: "cold", is: "naao", script: "หนาว", cat: "adjectives" },
  { en: "full (food)", is: "im", script: "อิ่ม", cat: "adjectives" },
  { en: "tired", is: "mueai", script: "เหนื่อย", cat: "adjectives" },
  { en: "happy", is: "dee jai", script: "ดีใจ", cat: "adjectives" },
  { en: "strong", is: "khaeng raeng", script: "แข็งแรง", cat: "adjectives" },
  { en: "soft", is: "num", script: "นุ่ม", cat: "adjectives" },
  { en: "hard", is: "khaeng", script: "แข็ง", cat: "adjectives" },
  { en: "new", is: "mai", script: "ใหม่", cat: "adjectives" },
  { en: "old (thing)", is: "kao", script: "เก่า", cat: "adjectives" },
  { en: "far", is: "kai", script: "ไกล", cat: "adjectives" },
  { en: "near", is: "kai", script: "ใกล้", cat: "adjectives" },
  { en: "fun / enjoyable", is: "muan", script: "สนุก", cat: "adjectives" },

  // TIME (20)
  { en: "today", is: "meu nee", script: "มื้อนี้", cat: "time" },
  { en: "yesterday", is: "meu waan", script: "มื้อวาน", cat: "time" },
  { en: "tomorrow", is: "meu eun", script: "มื้ออื่น", cat: "time" },
  { en: "day", is: "meu", script: "มื้อ", cat: "time" },
  { en: "night", is: "khuen", script: "คืน", cat: "time" },
  { en: "morning", is: "sao", script: "เช้า", cat: "time" },
  { en: "evening", is: "laeng", script: "แลง", cat: "time" },
  { en: "month", is: "duen", script: "เดือน", cat: "time" },
  { en: "year", is: "pii", script: "ปี", cat: "time" },
  { en: "week", is: "a-thit", script: "อาทิตย์", cat: "time" },
  { en: "hour", is: "suamong", script: "ซั่วโมง", cat: "time" },
  { en: "minute", is: "na-thi", script: "นาที", cat: "time" },
  { en: "now", is: "diao nee", script: "เดี๋ยวนี้", cat: "time" },
  { en: "later", is: "khoii", script: "เดี๋ยว", cat: "time" },
  { en: "early", is: "waao", script: "เช้า", cat: "time" },
  { en: "late", is: "saai", script: "สาย", cat: "time" },
  { en: "always", is: "thuk meu", script: "ทุกมื้อ", cat: "time" },
  { en: "sometimes", is: "bang khao", script: "บางคราว", cat: "time" },
  { en: "never", is: "baw khoi", script: "บ่เคย", cat: "time" },
  { en: "how long?", is: "naan thao dai?", script: "นานเท่าได๋?", cat: "time" },

  // EMOTIONS (20)
  { en: "happy", is: "dee jai", script: "ดีใจ", cat: "emotions" },
  { en: "sad", is: "saao jai", script: "เศร้าใจ", cat: "emotions" },
  { en: "angry", is: "khong jai", script: "โกรธ", cat: "emotions" },
  { en: "scared / afraid", is: "kua", script: "กัว", cat: "emotions" },
  { en: "to miss someone", is: "khit heung", script: "คิดฮอด", cat: "emotions" },
  { en: "love", is: "hak", script: "ฮัก", cat: "emotions" },
  { en: "to like", is: "mak", script: "มัก", cat: "emotions" },
  { en: "surprised", is: "tok jai", script: "ตกใจ", cat: "emotions" },
  { en: "shy", is: "aai", script: "อาย", cat: "emotions" },
  { en: "lonely", is: "ngeow", script: "เหงา", cat: "emotions" },
  { en: "bored", is: "buea", script: "เบื่อ", cat: "emotions" },
  { en: "excited", is: "tuen ten", script: "ตื่นเต้น", cat: "emotions" },
  { en: "proud", is: "phum jai", script: "ภูมิใจ", cat: "emotions" },
  { en: "jealous", is: "it-cha", script: "อิจฉา", cat: "emotions" },
  { en: "worried", is: "hen jai", script: "เป็นห่วง", cat: "emotions" },
  { en: "calm", is: "ngap", script: "เงียบ", cat: "emotions" },
  { en: "fun / joyful", is: "muan", script: "สนุก", cat: "emotions" },
  { en: "grateful", is: "khob jai laai", script: "ขอบใจหลาย", cat: "emotions" },
  { en: "to cry", is: "hong hai", script: "ฮ้องไห้", cat: "emotions" },
  { en: "to laugh", is: "hua", script: "ฮ่า", cat: "emotions" },
];
